package services

import (
	"bufio"
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log"
	"net/http"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"

	"kickrss/config"
	"kickrss/crud"
)

// OpenAI Chat Completion Structs
type ChatMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type ChatCompletionRequest struct {
	Model          string        `json:"model"`
	Messages       []ChatMessage `json:"messages"`
	ResponseFormat interface{}   `json:"response_format,omitempty"`
	MaxTokens      *int          `json:"max_tokens,omitempty"`
	Stream         bool          `json:"stream,omitempty"`
}

type ChatCompletionResponse struct {
	Choices []struct {
		Message struct {
			Content string `json:"content"`
		} `json:"message"`
	} `json:"choices"`
	Usage struct {
		PromptTokens     int `json:"prompt_tokens"`
		CompletionTokens int `json:"completion_tokens"`
		TotalTokens      int `json:"total_tokens"`
	} `json:"usage"`
}

type ChatCompletionStreamResponse struct {
	Choices []struct {
		Delta struct {
			Content string `json:"content"`
		} `json:"delta"`
		FinishReason string `json:"finish_reason"`
	} `json:"choices"`
}

// Clean JSON response block generated by LLM (removes markdown code block backticks if present)
func cleanJSONString(s string) string {
	s = strings.TrimSpace(s)
	// Remove markdown code block if present
	if strings.HasPrefix(s, "```") {
		// regex to remove ```json ... ``` or ``` ... ```
		re := regexp.MustCompile("(?s)^```(?:json)?\\n(.*)\\n```$")
		matches := re.FindStringSubmatch(s)
		if len(matches) > 1 {
			s = matches[1]
		} else {
			// Fallback: just strip first and last line
			lines := strings.Split(s, "\n")
			if len(lines) > 2 {
				s = strings.Join(lines[1:len(lines)-1], "\n")
			}
		}
	}
	return strings.TrimSpace(s)
}

func CallChatCompletion(messages []ChatMessage, taskName string, responseFormatJSON bool) (string, error) {
	cfg := config.GetAIConfig(taskName)
	if cfg.BaseURL == "" || cfg.APIKey == "" {
		return "", errors.New("LLM API base URL or API key is not configured")
	}

	url := fmt.Sprintf("%s/chat/completions", strings.TrimRight(cfg.BaseURL, "/"))
	reqBody := ChatCompletionRequest{
		Model:    cfg.Model,
		Messages: messages,
	}

	if responseFormatJSON {
		reqBody.ResponseFormat = map[string]string{"type": "json_object"}
	}
	if cfg.MaxTokens != nil {
		reqBody.MaxTokens = cfg.MaxTokens
	}

	jsonBytes, err := json.Marshal(reqBody)
	if err != nil {
		return "", err
	}

	req, err := http.NewRequest("POST", url, bytes.NewBuffer(jsonBytes))
	if err != nil {
		return "", err
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", cfg.APIKey))

	client := &http.Client{Timeout: 120 * time.Second}
	resp, err := client.Do(req)
	if err != nil || (err == nil && resp.StatusCode == http.StatusBadRequest) {
		if responseFormatJSON {
			if resp != nil && resp.Body != nil {
				resp.Body.Close()
			}
			reqBody.ResponseFormat = nil
			jsonBytesRetry, _ := json.Marshal(reqBody)
			reqRetry, errRetryReq := http.NewRequest("POST", url, bytes.NewBuffer(jsonBytesRetry))
			if errRetryReq == nil {
				reqRetry.Header.Set("Content-Type", "application/json")
				reqRetry.Header.Set("Authorization", fmt.Sprintf("Bearer %s", cfg.APIKey))
				respRetry, errRetry := client.Do(reqRetry)
				if errRetry == nil {
					resp = respRetry
					err = nil
				}
			}
		}
	}

	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		bodyBytes, _ := io.ReadAll(resp.Body)
		return "", fmt.Errorf("AI API returned status %d: %s", resp.StatusCode, string(bodyBytes))
	}

	var completionResp ChatCompletionResponse
	if err := json.NewDecoder(resp.Body).Decode(&completionResp); err != nil {
		return "", err
	}

	if completionResp.Usage.TotalTokens > 0 {
		crud.RecordTokenUsage(completionResp.Usage.PromptTokens, completionResp.Usage.CompletionTokens, completionResp.Usage.TotalTokens)
	}

	if len(completionResp.Choices) == 0 {
		return "", errors.New("AI API returned empty choices")
	}

	return completionResp.Choices[0].Message.Content, nil
}

// Helper to call OpenAI API in streaming mode and return connection reader
func CallChatCompletionStream(messages []ChatMessage, taskName string) (*http.Response, error) {
	cfg := config.GetAIConfig(taskName)
	if cfg.BaseURL == "" || cfg.APIKey == "" {
		return nil, errors.New("LLM API base URL or API key is not configured")
	}

	url := fmt.Sprintf("%s/chat/completions", strings.TrimRight(cfg.BaseURL, "/"))
	reqBody := ChatCompletionRequest{
		Model:    cfg.Model,
		Messages: messages,
		Stream:   true,
	}
	if cfg.MaxTokens != nil {
		reqBody.MaxTokens = cfg.MaxTokens
	}

	jsonBytes, err := json.Marshal(reqBody)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", url, bytes.NewBuffer(jsonBytes))
	if err != nil {
		return nil, err
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", cfg.APIKey))

	// No timeout set here because it's a stream connection
	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}

	if resp.StatusCode != http.StatusOK {
		bodyBytes, _ := io.ReadAll(resp.Body)
		resp.Body.Close()
		return nil, fmt.Errorf("AI API stream returned status %d: %s", resp.StatusCode, string(bodyBytes))
	}

	return resp, nil
}

// --- Specific Tasks ---

func GenerateSeedCategories(titles []string) ([]string, error) {
	if len(titles) == 0 {
		return nil, nil
	}

	prompt := `You are an expert RSS assistant. You are given a list of article titles from a single RSS feed.
Your task is to analyze these titles and generate a list of 3 to 10 distinct, cohesive categories (drawers) to organize this feed.
Follow these rules:
1. The categories must be in the same language as the titles (e.g. if titles are in Chinese, categories must be in Chinese).
2. The categories should have a reasonable granularity (not too broad, not too narrow).
3. Do not include a '未归类' (Uncategorized) category; it will be added automatically.
4. Output must be a valid JSON object matching this schema:
{
  "categories": ["Category 1", "Category 2", ...]
}`

	titlesText := ""
	for i, t := range titles {
		titlesText += fmt.Sprintf("%d. %s\n", i+1, t)
	}

	messages := []ChatMessage{
		{Role: "system", Content: prompt},
		{Role: "user", Content: fmt.Sprintf("Here are the titles of the articles from the feed:\n\n%s", titlesText)},
	}

	content, err := CallChatCompletion(messages, "seed", true)
	if err != nil {
		return nil, err
	}

	cleaned := cleanJSONString(content)
	type SeedCategoriesResponse struct {
		Categories []string `json:"categories"`
	}
	var respObj SeedCategoriesResponse
	if err := json.Unmarshal([]byte(cleaned), &respObj); err != nil {
		log.Printf("[AI] Failed to parse seed categories JSON: %s. Raw: %s", err, content)
		return nil, err
	}

	var cleanCategories []string
	for _, cat := range respObj.Categories {
		trimmed := strings.TrimSpace(cat)
		if trimmed != "" && trimmed != "未归类" {
			cleanCategories = append(cleanCategories, trimmed)
		}
	}

	return cleanCategories, nil
}

type ClassificationResult struct {
	ID        interface{} `json:"id"`
	Category  string      `json:"category"`
	Attention string      `json:"attention"`
}

func ClassifyEntriesBatch(allowedCategories []string, entries []map[string]interface{}, interestProfilePrompt string) ([]ClassificationResult, error) {
	if len(entries) == 0 {
		return nil, nil
	}

	var truncatedEntries []map[string]interface{}
	for _, entry := range entries {
		summaryStr := ""
		if s, ok := entry["summary"].(string); ok {
			summaryStr = s
		}
		runes := []rune(summaryStr)
		if len(runes) > 200 {
			summaryStr = string(runes[:200])
		}
		truncatedEntries = append(truncatedEntries, map[string]interface{}{
			"id":      entry["id"],
			"title":   entry["title"],
			"summary": summaryStr,
		})
	}

	categoriesList := strings.Join(allowedCategories, ", ")
	prompt := fmt.Sprintf(`请将以下文章归入合适的分类抽屉，并给出一个注意力分级。
可用的分类抽屉仅限于以下列表（必须精准拼写，若无法归入任何已有抽屉，则归入 '未归类'）：
[%s]

每一篇文章可用的注意力分级（attention）必须是 'read'（精读）, 'skim'（略读）, 或 'glance'（扫读）之一。
判定规则：
- 对于内容充实、有深度分析、或非常匹配用户阅读偏好的，给予 'read' 档。
- 对于快讯、产品发布、信息量一般的，给予 'skim' 档。
- 对于纯活动推广、广告、无关紧要的闲聊，给予 'glance' 档。

请直接输出一个 JSON 对象，其中包含 key "results"，对应的值是分类结果的列表，形如：
{
  "results": [
    {"id": 123, "category": "抽屉名字", "attention": "read"},
    {"id": 124, "category": "未归类", "attention": "skim"}
  ]
}`, categoriesList)

	if interestProfilePrompt != "" {
		prompt += fmt.Sprintf("\n\n用户的阅读习惯偏好指南如下，分类时请重要参考：\n%s", interestProfilePrompt)
	}

	entriesBytes, _ := json.Marshal(truncatedEntries)
	messages := []ChatMessage{
		{Role: "system", Content: prompt},
		{Role: "user", Content: string(entriesBytes)},
	}

	content, err := CallChatCompletion(messages, "classify", true)
	if err != nil {
		return nil, err
	}

	cleaned := cleanJSONString(content)
	type ClassificationResponse struct {
		Results []ClassificationResult `json:"results"`
	}
	var respObj ClassificationResponse
	if err := json.Unmarshal([]byte(cleaned), &respObj); err != nil {
		log.Printf("[AI] Failed to parse classification batch JSON: %s. Raw: %s", err, content)
		return nil, err
	}

	return respObj.Results, nil
}

func GetSummaryMessages(title, url, content string, length interface{}, summaryLang string) []ChatMessage {
	var lengthStr string
	switch v := length.(type) {
	case int:
		lengthStr = strconv.Itoa(v)
	case string:
		lengthStr = v
	default:
		lengthStr = ""
	}
	if lengthStr == "" {
		lengthStr = config.GlobalConfig.AI.SummaryLength
	}
	if summaryLang == "" {
		summaryLang = config.GlobalConfig.AI.SummaryLanguage
	}
	if summaryLang == "auto" || summaryLang == "" {
		summaryLang = config.GlobalConfig.SystemLanguage
	}
	if summaryLang == "" {
		summaryLang = "zh"
	}

	targetChars := 0
	isNumericLength := false
	if val, err := strconv.Atoi(lengthStr); err == nil {
		targetChars = val
		isNumericLength = true
	}

	var lengthDesc string
	var ruleDesc string
	var structureAdvice string
	var cnStructureAdvice string

	if isNumericLength {
		lengthDesc = fmt.Sprintf("proportional summary targeting approximately %d Chinese characters (around 1/10 of the clean text length)", targetChars)

		if targetChars >= 600 {
			structureAdvice = fmt.Sprintf("- For this length (%d characters), write a highly detailed, multi-paragraph, and structured summary. Break down the content into sections such as: Background/Context, Core Arguments/Key Points (explained with detail and evidence), Key Data/Findings, and Implications/Conclusions. Include specific examples, names, and numbers from the text to ensure depth and meet the length requirement.", targetChars)
			cnStructureAdvice = fmt.Sprintf("针对当前较长的目标字数（大约 %d 字），你必须撰写一份结构清晰、内容饱满的深度长摘要。部分观点需要展开论述，请分成多个段落进行详细论述，包含：背景与前言、核心观点与详细论据展开、关键数据或案例细节、总结与影响。请多写细节、逻辑展开，严禁三言两语草草了事，以确保字数足够饱满。", targetChars)
		} else if targetChars >= 300 {
			structureAdvice = fmt.Sprintf("- For this length (%d characters), write a detailed summary containing 2-3 structured paragraphs or 5-8 detailed bullet points. Ensure core takeaways and their supporting points are fully explained.", targetChars)
			cnStructureAdvice = fmt.Sprintf("针对当前中等目标字数（大约 %d 字），请撰写 2-3 个结构完整的段落，或者 5-8 个含有详细解释的要点。确保把核心事实、论据 and 结论表述清楚。", targetChars)
		} else {
			structureAdvice = fmt.Sprintf("- For this length (%d characters), write a concise summary containing 1-2 paragraphs or 3-5 bullet points.", targetChars)
			cnStructureAdvice = fmt.Sprintf("针对当前简短的目标字数（大约 %d 字），请撰写 1-2 个精炼的段落，或者 3-5 个核心要点。", targetChars)
		}

		ruleDesc = fmt.Sprintf("The summary should be high-quality, cover key takeaways, and strictly target approximately %d Chinese characters.\n"+
			"- CRITICAL: The generated summary MUST contain around %d Chinese characters. DO NOT make it too short. The target length is strictly %d characters.\n"+
			"- %s", targetChars, targetChars, targetChars, structureAdvice)
	} else if lengthStr == "short" {
		lengthDesc = "short and concise summary (typically 3 bullet points or 1 paragraph, around 150-200 characters for the summary)"
		ruleDesc = "The summary should be very brief and focus only on the most important takeaway."
	} else if lengthStr == "long" {
		lengthDesc = "long, detailed and comprehensive summary (typically 6-8 bullet points or 3-4 structured paragraphs, around 600-800 characters for the summary)"
		ruleDesc = "The summary should cover background context, core points/arguments, key facts/data, and final conclusions in detail."
	} else { // medium
		lengthDesc = "comprehensive and informative summary (typically 4-6 bullet points or 2 structured paragraphs, around 300-400 characters for the summary)"
		ruleDesc = "The summary should cover background context, core points/arguments, key facts/data, and final conclusions."
	}

	engName, localName, chnName := GetLanguageNames(summaryLang)

	var langRule string
	var reminder string

	if summaryLang != "" {
		langRule = fmt.Sprintf("CRITICAL: The summary must be written in %s (%s) ONLY, regardless of the original language of the article.\n"+
			"- If the article is in Chinese or English, you MUST translate the key concepts and write the summary in %s (%s).\n"+
			"- 必须且只能使用 %s (%s) 撰写 SUMMARY 部分，绝对不要使用原文语言（如中文或英文）来写摘要。", engName, localName, engName, localName, chnName, localName)

		if isNumericLength {
			langRule += fmt.Sprintf("\n- 必须写满大约 %d 个%s（汉字）（字数范围必须严格控制在 %d 到 %d 字之间）。\n"+
				"- 这是字数的硬性指令，请把观点铺开、细节写饱满，绝对不能偷懒缩短！\n"+
				"- 编写要求：%s", targetChars, chnName, int(float64(targetChars)*0.9), int(float64(targetChars)*1.15), cnStructureAdvice)
		}
		reminder = fmt.Sprintf("\n\nReminder: You MUST write the SUMMARY in %s (%s). (提示：请务必且只能使用 %s / %s 撰写摘要。)", engName, localName, chnName, localName)
	} else {
		langRule = "The summary must be in the same language as the article content."
		if isNumericLength {
			langRule += fmt.Sprintf("\n- CRITICAL: The generated summary MUST target approximately %d characters. DO NOT make it too short.\n- Requirements: %s", targetChars, structureAdvice)
		}
		reminder = ""
	}

	systemPrompt := fmt.Sprintf("You are an expert RSS assistant. You are given the title, URL, and full-text content of an article.\n"+
		"Your task is to:\n"+
		"1. Verify if the title is misleading or clickbait compared to the actual content.\n"+
		"2. Generate a %s.\n\n"+
		"Rules:\n"+
		"- %s\n"+
		"- If the content is empty or contains no text, reply exactly with: \"NO_CONTENT\"\n"+
		"- %s\n"+
		"- Formatting Guidelines (Extremely Important):\n"+
		"  - Use markdown formatting to make the summary highly readable.\n"+
		"  - Structure the summary primarily as a detailed bullet list starting with '-' (e.g., `- **Point Name**: Explanation`). Each bullet point should be highly informative, specific, and detailed.\n"+
		"  - You may introduce the summary with a very brief opening paragraph (1-2 sentences), but the core of the summary must be structured as detailed list items rather than plain paragraphs.\n"+
		"  - Selectively use double asterisks (`**text**`) to bold key conclusions, core arguments, or sentences that need focus to make the summary scannable.\n"+
		"- 格式与排版规范（极重要）：\n"+
		"  - 必须使用 Markdown 格式排版，确保摘要易读、易扫视。\n"+
		"  - 主要排版结构：必须以条目（无序列表 `- `）为核心排版结构，避免使用大段的文字叙述。每一个条目（例如：`- **核心要点**：详细细节与事实展开`）必须内容扎实、数据细节饱满，并合理换行展开。\n"+
		"  - 可以在最开头有一句非常简短的导语（1-2句），但整个摘要的主体必须是详细具体的条目列表。\n"+
		"  - 突出重点：选择性地将最重要的结论、核心词句或关键数据加粗（使用 `**加粗文本**`），让读者能一眼扫视出文章的精髓，但注意不要过度加粗。\n"+
		"- Format your response EXACTLY like this (do NOT translate the prefix keys 'CLICKBAIT_NOTE:' and 'SUMMARY:'):\n"+
		"CLICKBAIT_NOTE: <If the title is misleading, state the exact reason and clear up the discrepancy in 1 sentence. If NOT misleading, write NONE>\n"+
		"SUMMARY: <write the detailed summary here>", lengthDesc, ruleDesc, langRule)

	userPrompt := fmt.Sprintf("Title: %s\nURL: %s\nContent:\n%s%s", title, url, content, reminder)

	return []ChatMessage{
		{Role: "system", Content: systemPrompt},
		{Role: "user", Content: userPrompt},
	}
}

func GenerateSummarySync(title, url, text string, length int, summaryLang string) (string, error) {
	messages := GetSummaryMessages(title, url, text, length, summaryLang)
	return CallChatCompletion(messages, "summary", false)
}

func ParseAISummaryResponse(rawText string) (string, string) {
	clickbaitNote := ""
	summary := ""

	lines := strings.SplitN(rawText, "\n", 2)
	firstLine := ""
	if len(lines) > 0 {
		firstLine = lines[0]
	}
	rest := ""
	if len(lines) > 1 {
		rest = lines[1]
	}

	if strings.HasPrefix(firstLine, "CLICKBAIT_NOTE:") {
		noteVal := strings.TrimPrefix(firstLine, "CLICKBAIT_NOTE:")
		noteVal = strings.TrimSpace(noteVal)
		if strings.ToUpper(noteVal) != "NONE" && noteVal != "" {
			clickbaitNote = noteVal
		}
	}

	if strings.HasPrefix(rest, "SUMMARY:") {
		summary = strings.TrimPrefix(rest, "SUMMARY:")
		summary = strings.TrimSpace(summary)
	} else {
		// Fallback
		if rest != "" {
			summary = strings.TrimSpace(rest)
		} else {
			summary = strings.TrimSpace(rawText)
		}
	}

	return summary, clickbaitNote
}

type TopicPromotion struct {
	CategoryName string        `json:"category_name"`
	EntryIDs     []interface{} `json:"entry_ids"`
}

func IdentifyPromotableTopics(entries []map[string]interface{}, promoteThreshold int) ([]TopicPromotion, error) {
	if len(entries) == 0 {
		return nil, nil
	}

	prompt := fmt.Sprintf(`下面有一批最近未分类的 RSS 文章。请你分析它们的标题，识别出近期在该订阅源下反复出现的细分主题。
如果有某个特定细分话题的文章数量达到了 %d 篇或以上，请将其“提升”为一个独立的正式分类抽屉（抽屉名必须具体、针对特定话题，控制在 2-6 个汉字，例如：“SpaceX”、“大模型应用”、“一加手机发行”）。
对于被归入该主题的文章，请列出其对应的 ID。

请直接输出一个 JSON 对象，其中包含 key "promotions"，对应的值是提升主题的列表，格式形如：
{
  "promotions": [
    {"category_name": "SpaceX", "entry_ids": [12, 15, 18, 20, 25]}
  ]
}`, promoteThreshold)

	entriesBytes, _ := json.Marshal(entries)
	messages := []ChatMessage{
		{Role: "system", Content: prompt},
		{Role: "user", Content: string(entriesBytes)},
	}

	content, err := CallChatCompletion(messages, "classify", true)
	if err != nil {
		return nil, err
	}

	cleaned := cleanJSONString(content)
	type TopicPromotionsResponse struct {
		Promotions []TopicPromotion `json:"promotions"`
	}
	var respObj TopicPromotionsResponse
	if err := json.Unmarshal([]byte(cleaned), &respObj); err != nil {
		log.Printf("[AI] Failed to parse topic promotion JSON: %s. Raw: %s", err, content)
		return nil, err
	}

	return respObj.Promotions, nil
}

type CategoryMerge struct {
	Source string `json:"source"`
	Target string `json:"target"`
}

func IdentifyDuplicateCategories(categoryNames []string) ([]CategoryMerge, error) {
	if len(categoryNames) < 2 {
		return nil, nil
	}

	prompt := `你是一个 RSS 抽屉分类管理器。下面给出一组自定义分类抽屉的名字列表。
请分析它们，检查是否存在语义高度重复、只是表述略有不同的分类（例如：“人工智能”与“AI技术”、“iPhone 15”与“苹果手机新品”）。
如果存在，请识别出来，并决定将“源分类”（Source）合并到“目标分类”（Target，保留这个名字作为更规范的归宿）中。
注意：不要把完全不相关的分类合并（例如“电动汽车”和“半导体开发”不要合并）。

请直接输出一个 JSON 对象，其中包含 key "merges"，对应的值是合并任务的列表，格式形如：
{
  "merges": [
    {"source": "源分类名字A", "target": "目标分类名字B"}
  ]
}`

	messages := []ChatMessage{
		{Role: "system", Content: prompt},
		{Role: "user", Content: fmt.Sprintf("现有分类列表：\n%s", strings.Join(categoryNames, "\n"))},
	}

	content, err := CallChatCompletion(messages, "classify", true)
	if err != nil {
		return nil, err
	}

	cleaned := cleanJSONString(content)
	type CategoryMergesResponse struct {
		Merges []CategoryMerge `json:"merges"`
	}
	var respObj CategoryMergesResponse
	if err := json.Unmarshal([]byte(cleaned), &respObj); err != nil {
		log.Printf("[AI] Failed to parse category merge JSON: %s. Raw: %s", err, content)
		return nil, err
	}

	return respObj.Merges, nil
}

type UserInterestSnapshot struct {
	AttentionGuide    string                   `json:"attention_guide"`
	HighInterest      []map[string]interface{} `json:"high_interest"`
	LowInterest       []map[string]interface{} `json:"low_interest"`
	ConcentrationNote *string                  `json:"concentration_note"`
}

type scoredEngagement struct {
	score float64
	row   map[string]interface{}
}

func engagementScore(row map[string]interface{}) float64 {
	score := 0.0

	if bump, ok := row["manual_bump"].(string); ok {
		if bump == "read" {
			score += 5.0
		} else if bump == "glance" {
			score -= 3.0
		}
	}

	if fav, ok := row["favorited"].(int); ok && fav > 0 {
		score += 4.0
	}
	if openOrig, ok := row["opened_original"].(int); ok && openOrig > 0 {
		score += 3.0
	}
	if scrollBot, ok := row["scrolled_to_bottom"].(int); ok && scrollBot > 0 {
		score += 2.0
	}

	if dwell, ok := row["active_dwell_ms"].(int); ok {
		dwellMin := float64(dwell) / 60000.0
		if dwellMin > 2.0 {
			dwellMin = 2.0
		}
		score += dwellMin
	}

	if scrollPct, ok := row["scrolled_pct"].(float64); ok {
		score += scrollPct * 1.5
	} else if scrollPctInt, ok := row["scrolled_pct"].(int); ok {
		score += float64(scrollPctInt) * 1.5
	}

	return score
}

func AggregateUserInterestsSnapshot(engagementList []map[string]interface{}) (*UserInterestSnapshot, error) {
	if len(engagementList) == 0 {
		return nil, errors.New("engagement data list is empty")
	}

	scored := make([]scoredEngagement, len(engagementList))
	for i, r := range engagementList {
		scored[i] = scoredEngagement{
			score: engagementScore(r),
			row:   r,
		}
	}

	sort.Slice(scored, func(i, j int) bool {
		return scored[i].score > scored[j].score
	})

	var high []map[string]interface{}
	var low []map[string]interface{}
	for _, se := range scored {
		if se.score >= 4.0 {
			high = append(high, se.row)
		} else if se.score <= 0.0 {
			low = append(low, se.row)
		}
	}

	highLimit := 80
	if len(high) < highLimit {
		highLimit = len(high)
	}
	lowLimit := 80
	if len(low) < lowLimit {
		lowLimit = len(low)
	}

	var highTitles []string
	for _, r := range high[:highLimit] {
		feedName, _ := r["feed_name"].(string)
		title, _ := r["title"].(string)
		highTitles = append(highTitles, fmt.Sprintf("[%s] %s", feedName, title))
	}

	var lowTitles []string
	for _, r := range low[:lowLimit] {
		feedName, _ := r["feed_name"].(string)
		title, _ := r["title"].(string)
		lowTitles = append(lowTitles, fmt.Sprintf("[%s] %s", feedName, title))
	}

	highText := "（数据不足）"
	if len(highTitles) > 0 {
		var buf bytes.Buffer
		for _, t := range highTitles {
			buf.WriteString("- " + t + "\n")
		}
		highText = buf.String()
	}

	lowText := "（数据不足）"
	if len(lowTitles) > 0 {
		var buf bytes.Buffer
		for _, t := range lowTitles {
			buf.WriteString("- " + t + "\n")
		}
		lowText = buf.String()
	}

	prompt := fmt.Sprintf(`你是一个用户阅读行为分析助手。以下是某用户近30天的RSS阅读记录。

## 用户高度关注的文章（长时间阅读、滚动到底、收藏、查看原文、手动提升注意力）
%s
## 用户较少关注的文章（快速跳过、很少互动）
%s
请分析并输出以下 JSON（不要输出其他内容）：
{
  "high_interest": [
    {"topic": "主题名称（简短，4-10字）", "description": "一句话描述用户在这个主题上的关注点", "strength": "high 或 medium"}
  ],
  "low_interest": [
    {"topic": "主题名称", "description": "一句话描述"}
  ],
  "attention_guide": "一段自然语言，50-120字，概括用户的整体阅读倾向，供分类器参考。格式示例：'用户高度关注XX and XX方向，尤其是涉及XX的内容应标为read；对XX and XX类内容兴趣较低，可标为glance。'",
  "concentration_note": "如果 high_interest 中超过半数主题属于同一领域，输出一句带黑色幽默、毒舌、戏谑又一针见血的调侃，无情揭露用户偏科的信息茧房（30-60字），语气要傲娇或犀利，否则设为 null"
}

要求：
- high_interest 提取 3-8 个主题，按关注强度从高到低排列
- low_interest 提取 2-5 个主题
- 主题应跨订阅源归纳，不要按订阅源罗列
- 如果某类文章高参与和低参与中都有，说明用户对该主题的子方向有选择性，请在 description 中体现
- attention_guide 必须具体到可操作，不要说"用户关注科技"这种空话`, highText, lowText)

	messages := []ChatMessage{
		{Role: "system", Content: "You are a helpful reading behavior analyst."},
		{Role: "user", Content: prompt},
	}

	content, err := CallChatCompletion(messages, "profile", true)
	if err != nil {
		return nil, err
	}

	cleaned := cleanJSONString(content)
	var snapshot UserInterestSnapshot
	if err := json.Unmarshal([]byte(cleaned), &snapshot); err != nil {
		log.Printf("[AI] Failed to parse user interest profile JSON: %s. Raw: %s", err, content)
		return nil, err
	}

	return &snapshot, nil
}

// Estimate character count length in Chinese equivalent
func EstimateCleanTextLength(text string) int {
	// Simple runecount represents character length roughly in UTF-8
	return len([]rune(text))
}

// Stream reader helper for SSE server transmission
func ReadSSEResponse(resp *http.Response, onChunk func(string) error) error {
	reader := bufio.NewReader(resp.Body)
	for {
		line, err := reader.ReadString('\n')
		if err != nil {
			if err == io.EOF {
				break
			}
			return err
		}

		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}

		if strings.HasPrefix(line, "data: ") {
			data := strings.TrimPrefix(line, "data: ")
			if data == "[DONE]" {
				break
			}

			var streamResp ChatCompletionStreamResponse
			if err := json.Unmarshal([]byte(data), &streamResp); err == nil {
				if len(streamResp.Choices) > 0 {
					content := streamResp.Choices[0].Delta.Content
					if content != "" {
						if err := onChunk(content); err != nil {
							return err
						}
					}
					if streamResp.Choices[0].FinishReason == "stop" {
						break
					}
				}
			}
		}
	}
	return nil
}

// --- Translation Services ---

func DetectLanguage(text string) string {
	if text == "" {
		return "en"
	}
	// Regex for Chinese characters: \p{Han}
	re := regexp.MustCompile(`\p{Han}`)
	matches := re.FindAllString(text, -1)
	zhChars := len(matches)
	totalChars := len([]rune(text))
	if totalChars == 0 {
		return "en"
	}
	if float64(zhChars)/float64(totalChars) > 0.05 {
		return "zh"
	}
	return "en"
}

func GenerateTranslation(title string, text string, targetLang string) (string, error) {
	if text == "" {
		return "", nil
	}

	paragraphs := strings.Split(text, "\n")
	var chunks []string
	var currentChunk []string
	currentLen := 0

	for _, p := range paragraphs {
		pLen := len([]rune(p))
		if currentLen+pLen > 800 && len(currentChunk) > 0 {
			chunks = append(chunks, strings.Join(currentChunk, "\n"))
			currentChunk = []string{p}
			currentLen = pLen
		} else {
			currentChunk = append(currentChunk, p)
			currentLen += pLen + 1
		}
	}
	if len(currentChunk) > 0 {
		chunks = append(chunks, strings.Join(currentChunk, "\n"))
	}

	engName, localName, chnName := GetLanguageNames(targetLang)

	systemPrompt := fmt.Sprintf(`You are a professional translator.
Your task is to translate the given text into %s (%s).
Rules:
- Keep the paragraph structure and line breaks EXACTLY identical to the source text.
- Do NOT add any notes, explanations, introduction, or prefix. Output ONLY the translated paragraphs.
- Translate to %s (%s) faithfully, maintaining the original tone and style.
- CRITICAL: Regardless of the source language, you must translate it into %s (%s). Do NOT copy or output the original text if it is in a different language. You MUST output the translation in %s.
- 必须且只能将文本翻译为 %s (%s)，绝对不要直接输出原文！请输出完整的翻译后文本。`, engName, localName, engName, localName, engName, localName, localName, chnName, localName)

	type chunkResult struct {
		index int
		text  string
		err   error
	}

	resultsChan := make(chan chunkResult, len(chunks))
	sem := make(chan struct{}, 3) // Semaphore to limit concurrency

	for i, chunkText := range chunks {
		go func(idx int, cText string) {
			if strings.TrimSpace(cText) == "" {
				resultsChan <- chunkResult{index: idx, text: cText, err: nil}
				return
			}

			sem <- struct{}{}
			defer func() { <-sem }()

			userContent := fmt.Sprintf("Please translate the following text into %s (%s). Do NOT output the original text, only output the translated text:\n\n%s", engName, localName, cText)
			if chnName != "英文" {
				userContent = fmt.Sprintf("请将以下文本翻译为%s (%s)。请务必翻译，不要输出原文，只输出翻译后的文本：\n\n%s", chnName, localName, cText)
			}

			messages := []ChatMessage{
				{Role: "system", Content: systemPrompt},
				{Role: "user", Content: userContent},
			}

			translated, err := CallChatCompletion(messages, "summary", false)
			if err != nil {
				resultsChan <- chunkResult{index: idx, text: cText, err: err}
			} else {
				resultsChan <- chunkResult{index: idx, text: translated, err: nil}
			}
		}(i, chunkText)
	}

	translatedChunks := make([]string, len(chunks))
	for k := 0; k < len(chunks); k++ {
		res := <-resultsChan
		translatedChunks[res.index] = res.text
	}

	return strings.Join(translatedChunks, "\n"), nil
}

func GetEntryTranslation(entryID int, force bool) (map[string]interface{}, error) {
	entry, err := crud.GetEntryByID(entryID)
	if err != nil {
		return nil, err
	}
	if entry == nil {
		return nil, errors.New("entry not found")
	}

	targetLang := config.GlobalConfig.AI.SummaryLanguage
	if targetLang == "auto" || targetLang == "" {
		targetLang = config.GlobalConfig.SystemLanguage
	}
	if targetLang == "" {
		targetLang = "zh"
	}

	if force {
		_ = crud.DeleteTranslation(entryID)
		_ = crud.DeleteParagraphTranslations(entryID)
	} else {
		transRow, _ := crud.GetTranslation(entryID, targetLang)
		if transRow != nil {
			return map[string]interface{}{
				"translated_content": transRow.Content,
				"target_lang":        transRow.Lang,
				"status":             "ok",
			}, nil
		}
	}

	ftRow, _ := crud.GetEntryFulltext(entryID)
	var ftContent string
	if ftRow != nil {
		ftContent = ftRow.Content
	} else {
		ftContent = crud.CleanHTML(entry.RawContent)
	}

	if ftContent == "" || len([]rune(ftContent)) < 5 {
		return nil, errors.New("no content to translate")
	}

	sourceLang := DetectLanguage(ftContent)
	isSourceZh := (sourceLang == "zh" || sourceLang == "zh-hant")
	isTargetZh := (targetLang == "zh" || targetLang == "zh-hant")

	if sourceLang == targetLang || (isSourceZh && isTargetZh) {
		_ = crud.SaveTranslation(entryID, ftContent, targetLang)
		return map[string]interface{}{
			"translated_content": ftContent,
			"target_lang":        targetLang,
			"status":             "ok",
		}, nil
	}

	translated, err := GenerateTranslation(entry.Title, ftContent, targetLang)
	if err != nil {
		return nil, err
	}

	_ = crud.SaveTranslation(entryID, translated, targetLang)

	return map[string]interface{}{
		"translated_content": translated,
		"target_lang":        targetLang,
		"status":             "ok",
	}, nil
}

func TranslateEntryParagraph(entryID int, paraIndex int, text string) (map[string]interface{}, error) {
	entry, err := crud.GetEntryByID(entryID)
	if err != nil {
		return nil, err
	}
	if entry == nil {
		return nil, errors.New("entry not found")
	}

	targetLang := config.GlobalConfig.AI.SummaryLanguage
	if targetLang == "auto" || targetLang == "" {
		targetLang = config.GlobalConfig.SystemLanguage
	}
	if targetLang == "" {
		targetLang = "zh"
	}

	textToTranslate := strings.TrimSpace(text)
	if textToTranslate == "" {
		return map[string]interface{}{
			"translated_text": "",
			"status":          "ok",
		}, nil
	}

	cached, _ := crud.GetParagraphTranslation(entryID, paraIndex, targetLang)
	if cached != nil && cached.OriginalText == textToTranslate {
		return map[string]interface{}{
			"translated_text": cached.TranslatedText,
			"status":          "ok",
		}, nil
	}

	sourceLang := DetectLanguage(textToTranslate)
	isSourceZh := (sourceLang == "zh" || sourceLang == "zh-hant")
	isTargetZh := (targetLang == "zh" || targetLang == "zh-hant")

	translatedText := textToTranslate
	if !(sourceLang == targetLang || (isSourceZh && isTargetZh)) {
		translated, err := GenerateTranslation(entry.Title, textToTranslate, targetLang)
		if err == nil {
			translatedText = translated
		}
	}

	_ = crud.SaveParagraphTranslation(entryID, paraIndex, targetLang, textToTranslate, translatedText)

	return map[string]interface{}{
		"translated_text": translatedText,
		"status":          "ok",
	}, nil
}

func GetLanguageNames(langCode string) (string, string, string) {
	langMap := map[string][3]string{
		"zh":      {"Simplified Chinese (简体中文)", "简体中文", "简体中文"},
		"zh-hant": {"Traditional Chinese (繁体中文)", "繁體中文", "繁体中文"},
		"en":      {"English", "English", "英文"},
		"ja":      {"Japanese (日本語)", "日本語", "日语"},
		"ko":      {"Korean (한국어)", "한국어", "韩语"},
		"fr":      {"French (Français)", "Français", "法语"},
		"es":      {"Spanish (Español)", "Español", "西班牙语"},
		"de":      {"German (Deutsch)", "Deutsch", "德语"},
		"ru":      {"Russian (Русский)", "Русский", "俄语"},
		"pt":      {"Portuguese (Português)", "Português", "葡萄牙语"},
		"it":      {"Italian (Italiano)", "Italiano", "意大利语"},
	}
	if val, ok := langMap[langCode]; ok {
		return val[0], val[1], val[2]
	}
	return "Simplified Chinese (简体中文)", "简体中文", "简体中文" // default fallback
}
